/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Oop;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ozan
 */
public final class ChoseArticle extends javax.swing.JFrame {

    DefaultTableModel model;
    ArticleDao articleList;

    public ChoseArticle() {
        initComponents();
        Scanner fileScanner;
        model = (DefaultTableModel) articleTable.getModel();
        int counter = 0;
        String[] article = new String[5];
        
        /* Csv dosyasından içeriği alıp tabloya attık*/
        try {
            fileScanner = new Scanner(new FileInputStream("ACM.csv")).useDelimiter(",\"|\",\"|\",|\n");

            fileScanner.nextLine();// ilk satırı bos geçmek için
            while (fileScanner.hasNext()) {
                article[counter] = fileScanner.next();

                if (counter == 4) {
                    model.addRow(article);
                    counter = -1;// altta arttıgı ıcın -1 den baslattık .

                }
                counter++;
            }

        } catch (FileNotFoundException e) {
            System.out.println("File Not Found");
        }
    }

    public void selectedArticleByUser() {
        /*  tabloda Secili olan makaleleri article liste ekliyoruz secili olmayanları siliyoruz  */

        Article temp;
        articleList = new ArticleDaoImp();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            if (model.getValueAt(i, 5) != null) {

                temp = new Article(Integer.parseInt(((String) model.getValueAt(i, 0)).trim()), (String) model.getValueAt(i, 1),
                        (String) model.getValueAt(i, 2), (String) model.getValueAt(i, 3), Integer.parseInt(((String) model.getValueAt(i, 0)).trim()));

                articleList.addArticle(temp);
            } else {
                model.removeRow(i);
            }
        }

    }

    public void selectArticleByRandomize() {
        /*tabloda 10 tane rastgele eleman secer*/

        int iteration = 10;
        for (int i = 0; i < iteration; i++) {

            Random randomNumber = new Random();
            int number = randomNumber.nextInt(2294) + 1;
            if (model.getValueAt(number, 5) == null) {
                model.setValueAt(true, number, 5);
            } else {
                iteration++;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        articleTable = new javax.swing.JTable();
        downloadBtn = new javax.swing.JButton();
        randomBtn = new javax.swing.JButton();
        garantiSec = new javax.swing.JButton();
        inserDbBtn = new javax.swing.JButton();
        compareBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Ekran");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        articleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Title", "Authors", "Venue", "Year", "Seç"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        articleTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(articleTable);
        if (articleTable.getColumnModel().getColumnCount() > 0) {
            articleTable.getColumnModel().getColumn(5).setResizable(false);
        }

        downloadBtn.setText("Secilenleri İndir");
        downloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadBtnActionPerformed(evt);
            }
        });

        randomBtn.setText("Rastgele 10 Makale");
        randomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBtnActionPerformed(evt);
            }
        });

        garantiSec.setText("Garanti Seç");
        garantiSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garantiSecActionPerformed(evt);
            }
        });

        inserDbBtn.setText("Db ye Aktar");
        inserDbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserDbBtnActionPerformed(evt);
            }
        });

        compareBtn.setText("Analiz");
        compareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(downloadBtn)
                .addGap(18, 18, 18)
                .addComponent(randomBtn)
                .addGap(18, 18, 18)
                .addComponent(garantiSec)
                .addGap(18, 18, 18)
                .addComponent(inserDbBtn)
                .addGap(18, 18, 18)
                .addComponent(compareBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downloadBtn)
                    .addComponent(randomBtn)
                    .addComponent(garantiSec)
                    .addComponent(inserDbBtn)
                    .addComponent(compareBtn))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadBtnActionPerformed
        /* download butonuna basınca article liste atılmıs olan butun makaleleri indirir ve
           makalenın ındırıldıgı yeri article objesının ıcındekı locatıon degıskenıne atar
            daha sonra bu adresı dosyayı okumak ıcın kullandık*/
        selectedArticleByUser();
        JOptionPane.showMessageDialog(null, "Article which they are selected add article list and Download process begins !", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        for (Article a : articleList.getAllArticles()) {

            DownloadPdf pdf = new DownloadPdf();
            a.setLocation(pdf.DownloadPdf(a.getId()));
            PdfReader reader = new PdfReader();
            a.setContent(reader.readPdf(a.getLocation()));

        }
    }//GEN-LAST:event_downloadBtnActionPerformed

    private void randomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBtnActionPerformed
        //10 tane makale rastgele secen buton methodu direk içine mi yazsak ?
        selectArticleByRandomize();
        JOptionPane.showMessageDialog(null, "10 articles are selected by randomize !", "Information Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_randomBtnActionPerformed

    private void garantiSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garantiSecActionPerformed
        // içeriği düzgün olan daha once belırlenmıs makaleleri secer 

        for (int i = 0; i < model.getRowCount() - 1; i++) {

            if (Integer.parseInt((String) model.getValueAt(i, 0)) == 304582 || Integer.parseInt((String) model.getValueAt(i, 0)) == 304584 || Integer.parseInt((String) model.getValueAt(i, 0)) == 304585 || Integer.parseInt((String) model.getValueAt(i, 0)) == 304590 || Integer.parseInt((String) model.getValueAt(i, 0)) == 306124 || Integer.parseInt((String) model.getValueAt(i, 0)) == 304586 || Integer.parseInt((String) model.getValueAt(i, 0)) == 304587 || Integer.parseInt((String) model.getValueAt(i, 0)) == 304589 || Integer.parseInt((String) model.getValueAt(i, 0)) == 306102 || Integer.parseInt((String) model.getValueAt(i, 0)) == 304235) {

                model.setValueAt(true, i, 5);
            }
        }
        selectedArticleByUser();

    }//GEN-LAST:event_garantiSecActionPerformed

    private void inserDbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserDbBtnActionPerformed
        // arraylistteki elemanları dbye ekler
        articleList.insertDb();
    }//GEN-LAST:event_inserDbBtnActionPerformed

    private void compareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareBtnActionPerformed
        // TODO add your handling code here:
        Analyze analyzeScreen = new Analyze(articleList.getAllArticles());
        analyzeScreen.Analyzer(articleList.getAllArticles());
    }//GEN-LAST:event_compareBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoseArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoseArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoseArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoseArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoseArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable articleTable;
    private javax.swing.JButton compareBtn;
    private javax.swing.JButton downloadBtn;
    private javax.swing.JButton garantiSec;
    private javax.swing.JButton inserDbBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton randomBtn;
    // End of variables declaration//GEN-END:variables
}
